const inventory = {
  bread: [
    {
      breadType: "Sourdough",
      description: "Tangy, chewy bread with a crisp crust",
      price: 5.0,
      weight: 680,
      shelfLife: "5 days",
      ingredients: ["Flour", "Water", "Sourdough starter", "Salt"],
      stock: 20,
    },
    {
      breadType: "Whole Wheat",
      description: "Hearty bread with a nutty flavor",
      price: 4.5,
      weight: 680,
      shelfLife: "5 days",
      ingredients: ["Whole wheat flour", "Water", "Honey", "Yeast", "Salt"],
      stock: 48,
    },
    {
      breadType: "Baguette",
      description: "Classic French bread with a crisp crust",
      price: 3.0,
      weight: 454,
      shelfLife: "3 days",
      ingredients: ["Flour", "Water", "Yeast", "Salt"],
      stock: 20,
    },
    {
      breadType: "Ciabatta",
      description: "Italian bread with a light, airy texture",
      price: 4.0,
      weight: 454,
      shelfLife: "3 days",
      ingredients: ["Flour", "Water", "Yeast", "Olive oil", "Salt"],
      stock: 36,
    },
    {
      breadType: "Rye Bread",
      description: "Dense, flavorful bread with a dark crust",
      price: 5.5,
      weight: 680,
      shelfLife: "7 days",
      ingredients: [
        "Rye flour",
        "Bread flour",
        "Water",
        "Molasses",
        "Caraway seeds",
        "Yeast",
        "Salt",
      ],
      stock: 20,
    },
    {
      breadType: "Multigrain Bread",
      description: "Hearty bread with a variety of grains",
      price: 5.0,
      weight: 680,
      shelfLife: "5 days",
      ingredients: [
        "Whole wheat flour",
        "Oats",
        "Flax seeds",
        "Sunflower seeds",
        "Water",
        "Honey",
        "Yeast",
        "Salt",
      ],
      stock: 0,
    },
  ],
  pastry: [
    {
      pastryType: "Croissant",
      description: "Buttery, flaky pastry with a crescent shape",
      price: 2.5,
      weight: 70,
      ingredients: [
        "Flour",
        "Butter",
        "Water",
        "Yeast",
        "Sugar",
        "Salt",
        "Egg wash",
      ],
      stock: 60,
    },
    {
      pastryType: "Pain au Chocolat",
      description: "Chocolate-filled croissant",
      price: 3.0,
      weight: 85,
      ingredients: [
        "Flour",
        "Butter",
        "Water",
        "Yeast",
        "Sugar",
        "Salt",
        "Chocolate",
        "Egg wash",
      ],
      stock: 24,
    },
    {
      pastryType: "Almond Croissant",
      description: "Croissant filled with almond cream",
      price: 3.5,
      weight: 100,
      ingredients: [
        "Flour",
        "Butter",
        "Water",
        "Yeast",
        "Sugar",
        "Salt",
        "Almond cream",
        "Egg wash",
      ],
      stock: 12,
    },
    {
      pastryType: "Danish Pastry",
      description: "Sweet pastry with fruit or cream cheese filling",
      price: 3.0,
      weight: 120,
      ingredients: [
        "Flour",
        "Butter",
        "Water",
        "Yeast",
        "Sugar",
        "Salt",
        "Fruit/Cream cheese",
      ],
      stock: 12,
    },
  ],
  buns: [
    {
      bunType: "Dinner Roll",
      description: "Soft, fluffy roll",
      price: 1.0,
      weight: 50,
      ingredients: [
        "Flour",
        "Water",
        "Milk",
        "Butter",
        "Yeast",
        "Sugar",
        "Salt",
      ],
      stock: 120,
    },
    {
      bunType: "Hamburger Bun",
      description: "Soft, round bun with sesame seeds",
      price: 1.25,
      weight: 60,
      ingredients: [
        "Flour",
        "Water",
        "Milk",
        "Butter",
        "Yeast",
        "Sugar",
        "Salt",
        "Sesame seeds",
      ],
      stock: 60,
    },
    {
      bunType: "Hot Dog Bun",
      description: "Soft, elongated bun",
      price: 1.0,
      weight: 55,
      ingredients: [
        "Flour",
        "Water",
        "Milk",
        "Butter",
        "Yeast",
        "Sugar",
        "Salt",
      ],
      stock: 48,
    },
    {
      bunType: "Brioche Bun",
      description: "Rich, buttery bun",
      price: 1.5,
      weight: 70,
      ingredients: [
        "Flour",
        "Milk",
        "Butter",
        "Eggs",
        "Yeast",
        "Sugar",
        "Salt",
      ],
      stock: 48,
    },
    {
      bunType: "Cinnamon Roll",
      description: "Sweet roll with cinnamon and sugar filling",
      price: 2.0,
      weight: 90,
      ingredients: [
        "Flour",
        "Milk",
        "Butter",
        "Yeast",
        "Sugar",
        "Salt",
        "Cinnamon",
        "Sugar",
        "Icing",
      ],
      stock: 24,
    },
    {
      bunType: "Sticky Bun",
      description: "Sweet roll with sticky caramel topping",
      price: 2.25,
      weight: 100,
      ingredients: [
        "Flour",
        "Milk",
        "Butter",
        "Yeast",
        "Sugar",
        "Salt",
        "Brown sugar",
        "Pecans",
        "Caramel sauce",
      ],
      stock: 24,
    },
    {
      bunType: "Chelsea Bun",
      description:
        "Sweet roll with currants and lemon peel, topped with sugar glaze",
      price: 2.0,
      weight: 90,
      ingredients: [
        "Flour",
        "Milk",
        "Butter",
        "Yeast",
        "Sugar",
        "Salt",
        "Currants",
        "Lemon peel",
        "Sugar glaze",
      ],
      stock: 36,
    },
    {
      bunType: "Fruit Bun (Hot Cross Bun)",
      description: "Spiced bun with dried fruit, typically eaten during Easter",
      price: 1.75,
      weight: 80,
      ingredients: [
        "Flour",
        "Milk",
        "Butter",
        "Yeast",
        "Sugar",
        "Salt",
        "Spices",
        "Dried fruit",
        "Icing",
      ],
      stock: 24,
    },
  ],
};

// Exporting the inventory for use in other parts of the project
module.exports = inventory;
